<div class="main">
<div id="sofa-index">
  <div class="swiper-container swiper-banner">
    <div class="swiper-wrapper">
       <div class="swiper-slide banner-slide">
          <div class="banner-img" style="background-image: url(https://gw.alipayobjects.com/zos/rmsportal/UuEmwhceJUZcZcefEXlY.png)"></div>
          <div class="banner-content">
            <h3>SOFA Ark</h3>
            <p>SOFA Ark 是一款基于 Java 实现的轻量级类隔离加载容器；既可以用在普通应用上，又可以用在 Spring Boot 应用上。</p>
            <div class="btn-list">
                <a class="btn btn-white" href="/sofastack.github.io/docs">快速开始</a>
                <a class="btn btn-ghost" href="https://github.com/alipay">Github</a>
            </div>
          </div>
        </div>
    </div>
  </div>
    </div>
  </div>
</div>
<script src="https://gw.alipayobjects.com/os/skylark/QHIPXYQxUqPlaPVrLraR.js" type="text/javascript" charset="utf-8"></script>
<script src="https://gw.alipayobjects.com/os/skylark/guebsXkbCSEPVznzGAMq.js"></script>
    </div>
<div style="display: none">
  <script src="https://s19.cnzz.com/z_stat.php?id=1268345961&web_id=1268345961" language="JavaScript"></script>
</div>


