<div class="ant-row footer">
  <div class="footer-content">
    <div class="ant-row footer-desc">
      <div class="ant-col-8 ant-col-offset-2 footer-team">
        <h4>SOFA</h4>
        <p><a href="http://github.com/sofastack">首页</a></p>
        <p><a href="http://sofastack.github.io">文档</a></p>
      </div>
      <div class="ant-col-4 ant-col-offset-2 footer-friend">
        <h4>社区</h4>
        <p><a href="http://github.com/sofastack">Github</a></p>
        <p><a href="http://github.com/sofastack">Issues</a></p>
      </div>
      <div class="ant-col-6 ant-col-offset-2 footer-contact">
      
      </div>
    </div>
    <div class="copyright">
    </div>
  </div>
</div>